# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\main.ui',
# licensing of '.\uis\main.ui' applies.
#
# Created: Wed Sep 16 19:28:57 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 810)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 810))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 810))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 170, 981, 631))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_geral = QtWidgets.QWidget()
        self.tab_geral.setObjectName("tab_geral")
        self.grp_endereco = QtWidgets.QGroupBox(self.tab_geral)
        self.grp_endereco.setGeometry(QtCore.QRect(10, 270, 551, 181))
        self.grp_endereco.setObjectName("grp_endereco")
        self.label_5 = QtWidgets.QLabel(self.grp_endereco)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_5.setObjectName("label_5")
        self.edt_end_tip_logradouro = QtWidgets.QLineEdit(self.grp_endereco)
        self.edt_end_tip_logradouro.setGeometry(QtCore.QRect(90, 20, 141, 22))
        self.edt_end_tip_logradouro.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_end_tip_logradouro.setObjectName("edt_end_tip_logradouro")
        self.label_8 = QtWidgets.QLabel(self.grp_endereco)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.label_8.setObjectName("label_8")
        self.edt_end_logradouro = QtWidgets.QLineEdit(self.grp_endereco)
        self.edt_end_logradouro.setGeometry(QtCore.QRect(90, 50, 451, 22))
        self.edt_end_logradouro.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_end_logradouro.setObjectName("edt_end_logradouro")
        self.edt_end_num = QtWidgets.QLineEdit(self.grp_endereco)
        self.edt_end_num.setGeometry(QtCore.QRect(90, 80, 81, 22))
        self.edt_end_num.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_end_num.setObjectName("edt_end_num")
        self.label_9 = QtWidgets.QLabel(self.grp_endereco)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.grp_endereco)
        self.label_10.setGeometry(QtCore.QRect(180, 80, 101, 16))
        self.label_10.setObjectName("label_10")
        self.edt_end_complemento = QtWidgets.QLineEdit(self.grp_endereco)
        self.edt_end_complemento.setGeometry(QtCore.QRect(270, 80, 271, 22))
        self.edt_end_complemento.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_end_complemento.setObjectName("edt_end_complemento")
        self.edt_end_cep = QtWidgets.QLineEdit(self.grp_endereco)
        self.edt_end_cep.setGeometry(QtCore.QRect(430, 110, 111, 22))
        self.edt_end_cep.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_end_cep.setMaxLength(10)
        self.edt_end_cep.setObjectName("edt_end_cep")
        self.label_11 = QtWidgets.QLabel(self.grp_endereco)
        self.label_11.setGeometry(QtCore.QRect(390, 110, 31, 16))
        self.label_11.setObjectName("label_11")
        self.edt_end_bairro = QtWidgets.QLineEdit(self.grp_endereco)
        self.edt_end_bairro.setGeometry(QtCore.QRect(90, 110, 291, 22))
        self.edt_end_bairro.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_end_bairro.setObjectName("edt_end_bairro")
        self.label_12 = QtWidgets.QLabel(self.grp_endereco)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 101, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.grp_endereco)
        self.label_13.setGeometry(QtCore.QRect(10, 140, 101, 16))
        self.label_13.setObjectName("label_13")
        self.edt_end_municipio = QtWidgets.QLineEdit(self.grp_endereco)
        self.edt_end_municipio.setGeometry(QtCore.QRect(90, 140, 361, 22))
        self.edt_end_municipio.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_end_municipio.setObjectName("edt_end_municipio")
        self.label_14 = QtWidgets.QLabel(self.grp_endereco)
        self.label_14.setGeometry(QtCore.QRect(470, 140, 31, 16))
        self.label_14.setObjectName("label_14")
        self.edt_end_uf = QtWidgets.QLineEdit(self.grp_endereco)
        self.edt_end_uf.setGeometry(QtCore.QRect(500, 140, 41, 22))
        self.edt_end_uf.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_end_uf.setObjectName("edt_end_uf")
        self.grp_estrangeiro = QtWidgets.QGroupBox(self.tab_geral)
        self.grp_estrangeiro.setGeometry(QtCore.QRect(10, 220, 391, 51))
        self.grp_estrangeiro.setObjectName("grp_estrangeiro")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.grp_estrangeiro)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 371, 26))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.formLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.edt_cidade = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.edt_cidade.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_cidade.setObjectName("edt_cidade")
        self.horizontalLayout_2.addWidget(self.edt_cidade)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.edt_pais = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.edt_pais.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_pais.setObjectName("edt_pais")
        self.horizontalLayout_2.addWidget(self.edt_pais)
        self.gpr_contatos = QtWidgets.QGroupBox(self.tab_geral)
        self.gpr_contatos.setGeometry(QtCore.QRect(10, 450, 391, 151))
        self.gpr_contatos.setObjectName("gpr_contatos")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.gpr_contatos)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(114, 20, 191, 88))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_17.setObjectName("label_17")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.edt_tel1 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.edt_tel1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_tel1.setMaxLength(10)
        self.edt_tel1.setObjectName("edt_tel1")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edt_tel1)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_18.setObjectName("label_18")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.edt_tel3 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.edt_tel3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_tel3.setMaxLength(10)
        self.edt_tel3.setObjectName("edt_tel3")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edt_tel3)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_22.setObjectName("label_22")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.edt_tel2 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.edt_tel2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_tel2.setMaxLength(10)
        self.edt_tel2.setObjectName("edt_tel2")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edt_tel2)
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.gpr_contatos)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 96, 88))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_19.setObjectName("label_19")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.edt_ddd1 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.edt_ddd1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_ddd1.setMaxLength(2)
        self.edt_ddd1.setObjectName("edt_ddd1")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edt_ddd1)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_20.setObjectName("label_20")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.edt_ddd2 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.edt_ddd2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_ddd2.setMaxLength(2)
        self.edt_ddd2.setObjectName("edt_ddd2")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edt_ddd2)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_21.setObjectName("label_21")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.edt_ddd3 = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.edt_ddd3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_ddd3.setMaxLength(2)
        self.edt_ddd3.setObjectName("edt_ddd3")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edt_ddd3)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.gpr_contatos)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 110, 351, 26))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        self.edt_email = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.edt_email.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_email.setObjectName("edt_email")
        self.horizontalLayout_3.addWidget(self.edt_email)
        self.gpr_simples = QtWidgets.QGroupBox(self.tab_geral)
        self.gpr_simples.setGeometry(QtCore.QRect(10, 140, 391, 80))
        self.gpr_simples.setObjectName("gpr_simples")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.gpr_simples)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 19, 371, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        self.edt_simples = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.edt_simples.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_simples.setObjectName("edt_simples")
        self.horizontalLayout_5.addWidget(self.edt_simples)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.gpr_simples)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 181, 26))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_6.addWidget(self.label_27)
        self.edt_dt_op_simples = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.edt_dt_op_simples.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_dt_op_simples.setObjectName("edt_dt_op_simples")
        self.horizontalLayout_6.addWidget(self.edt_dt_op_simples)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.gpr_simples)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(200, 50, 181, 26))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_10.addWidget(self.label_30)
        self.edt_dt_ex_simples = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.edt_dt_ex_simples.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_dt_ex_simples.setObjectName("edt_dt_ex_simples")
        self.horizontalLayout_10.addWidget(self.edt_dt_ex_simples)
        self.grp_sit_especial = QtWidgets.QGroupBox(self.tab_geral)
        self.grp_sit_especial.setGeometry(QtCore.QRect(410, 140, 261, 81))
        self.grp_sit_especial.setObjectName("grp_sit_especial")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.grp_sit_especial)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 241, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_9.addWidget(self.label_29)
        self.edt_especial = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.edt_especial.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_especial.setObjectName("edt_especial")
        self.horizontalLayout_9.addWidget(self.edt_especial)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.grp_sit_especial)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 181, 26))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_7.addWidget(self.label_28)
        self.edt_dt_especial = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.edt_dt_especial.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_dt_especial.setObjectName("edt_dt_especial")
        self.horizontalLayout_7.addWidget(self.edt_dt_especial)
        self.groupBox = QtWidgets.QGroupBox(self.tab_geral)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 581, 121))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 541, 31))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_16.setObjectName("label_16")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.edt_natureza = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.edt_natureza.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_natureza.setObjectName("edt_natureza")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edt_natureza)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 50, 291, 31))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.edt_dt_ini_atividade = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.edt_dt_ini_atividade.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_dt_ini_atividade.setObjectName("edt_dt_ini_atividade")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edt_dt_ini_atividade)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 241, 26))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.edt_capital = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.edt_capital.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_capital.setInputMask("")
        self.edt_capital.setFrame(True)
        self.edt_capital.setClearButtonEnabled(False)
        self.edt_capital.setObjectName("edt_capital")
        self.horizontalLayout_4.addWidget(self.edt_capital)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(450, 50, 101, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_8.addWidget(self.label_26)
        self.edt_mei = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.edt_mei.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_mei.setObjectName("edt_mei")
        self.horizontalLayout_8.addWidget(self.edt_mei)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(260, 80, 291, 26))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout.addWidget(self.label_31)
        self.edt_porte = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.edt_porte.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_porte.setObjectName("edt_porte")
        self.horizontalLayout.addWidget(self.edt_porte)
        self.grp_situacao = QtWidgets.QGroupBox(self.tab_geral)
        self.grp_situacao.setGeometry(QtCore.QRect(680, 10, 291, 231))
        self.grp_situacao.setObjectName("grp_situacao")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.grp_situacao)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 271, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_situacao = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_situacao.setText("")
        self.lbl_situacao.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_situacao.setObjectName("lbl_situacao")
        self.verticalLayout.addWidget(self.lbl_situacao)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.grp_situacao)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 231, 31))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.edt_data_situacao = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edt_data_situacao.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_data_situacao.setObjectName("edt_data_situacao")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edt_data_situacao)
        self.label_4 = QtWidgets.QLabel(self.grp_situacao)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 106, 24))
        self.label_4.setObjectName("label_4")
        self.edt_motivo_situacao = QtWidgets.QTextEdit(self.grp_situacao)
        self.edt_motivo_situacao.setGeometry(QtCore.QRect(10, 120, 271, 101))
        self.edt_motivo_situacao.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_motivo_situacao.setObjectName("edt_motivo_situacao")
        self.tabWidget.addTab(self.tab_geral, "")
        self.tab_socios = QtWidgets.QWidget()
        self.tab_socios.setObjectName("tab_socios")
        self.table_socios = QtWidgets.QTableView(self.tab_socios)
        self.table_socios.setGeometry(QtCore.QRect(0, 0, 981, 601))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_socios.setFont(font)
        self.table_socios.setObjectName("table_socios")
        self.tabWidget.addTab(self.tab_socios, "")
        self.tab_cnaes = QtWidgets.QWidget()
        self.tab_cnaes.setObjectName("tab_cnaes")
        self.table_cnae = QtWidgets.QTableView(self.tab_cnaes)
        self.table_cnae.setGeometry(QtCore.QRect(0, 40, 981, 561))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_cnae.setFont(font)
        self.table_cnae.setObjectName("table_cnae")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.tab_cnaes)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 951, 26))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_12.addWidget(self.label_32)
        self.edt_cnae = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.edt_cnae.setObjectName("edt_cnae")
        self.horizontalLayout_12.addWidget(self.edt_cnae)
        self.tabWidget.addTab(self.tab_cnaes, "")
        self.tab_mapa = QtWidgets.QWidget()
        self.tab_mapa.setObjectName("tab_mapa")
        self.webEngineView = QWebEngineView(self.tab_mapa)
        self.webEngineView.setEnabled(True)
        self.webEngineView.setGeometry(QtCore.QRect(0, 0, 971, 571))
        self.webEngineView.setUrl(QtCore.QUrl("file:///D:/Vilquer/Documents/GitHub/PySide/Pyside_Python/CNPJ-full-PySide/resources/rede.PNG"))
        self.webEngineView.setZoomFactor(1.0)
        self.webEngineView.setObjectName("webEngineView")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.tab_mapa)
        self.commandLinkButton.setGeometry(QtCore.QRect(840, 570, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(6)
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.sld_nivel = QtWidgets.QSlider(self.tab_mapa)
        self.sld_nivel.setGeometry(QtCore.QRect(580, 580, 160, 20))
        self.sld_nivel.setMinimum(1)
        self.sld_nivel.setMaximum(6)
        self.sld_nivel.setPageStep(1)
        self.sld_nivel.setProperty("value", 1)
        self.sld_nivel.setOrientation(QtCore.Qt.Horizontal)
        self.sld_nivel.setObjectName("sld_nivel")
        self.label_33 = QtWidgets.QLabel(self.tab_mapa)
        self.label_33.setGeometry(QtCore.QRect(530, 580, 31, 16))
        self.label_33.setObjectName("label_33")
        self.lbl_nivel = QtWidgets.QLabel(self.tab_mapa)
        self.lbl_nivel.setGeometry(QtCore.QRect(560, 580, 31, 16))
        self.lbl_nivel.setText("")
        self.lbl_nivel.setObjectName("lbl_nivel")
        self.tabWidget.addTab(self.tab_mapa, "")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 321, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_cnpj = QtWidgets.QLabel(self.frame)
        self.lbl_cnpj.setEnabled(True)
        self.lbl_cnpj.setGeometry(QtCore.QRect(20, 10, 55, 16))
        self.lbl_cnpj.setObjectName("lbl_cnpj")
        self.edt_cnpj = QtWidgets.QLineEdit(self.frame)
        self.edt_cnpj.setGeometry(QtCore.QRect(70, 10, 191, 22))
        self.edt_cnpj.setMaxLength(18)
        self.edt_cnpj.setClearButtonEnabled(False)
        self.edt_cnpj.setObjectName("edt_cnpj")
        self.btn_pesquisar = QtWidgets.QPushButton(self.frame)
        self.btn_pesquisar.setGeometry(QtCore.QRect(210, 40, 93, 28))
        self.btn_pesquisar.setAutoDefault(True)
        self.btn_pesquisar.setDefault(True)
        self.btn_pesquisar.setObjectName("btn_pesquisar")
        self.btn_limpar = QtWidgets.QPushButton(self.frame)
        self.btn_limpar.setGeometry(QtCore.QRect(260, 10, 21, 21))
        self.btn_limpar.setIconSize(QtCore.QSize(10, 10))
        self.btn_limpar.setFlat(False)
        self.btn_limpar.setObjectName("btn_limpar")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 100, 801, 66))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.edt_razao_social = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edt_razao_social.setEnabled(True)
        self.edt_razao_social.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_razao_social.setObjectName("edt_razao_social")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edt_razao_social)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.edt_nome_fantasia = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edt_nome_fantasia.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_nome_fantasia.setObjectName("edt_nome_fantasia")
        self.horizontalLayout_11.addWidget(self.edt_nome_fantasia)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.edt_matriz = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edt_matriz.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edt_matriz.setObjectName("edt_matriz")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.edt_matriz)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.edt_cnpj, self.btn_pesquisar)
        MainWindow.setTabOrder(self.btn_pesquisar, self.btn_limpar)
        MainWindow.setTabOrder(self.btn_limpar, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Pesquisa RFB", None, -1))
        self.grp_endereco.setTitle(QtWidgets.QApplication.translate("MainWindow", "Endereço", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Tipo Logra.", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Logradouro", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Número", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Complemento", None, -1))
        self.edt_end_cep.setInputMask(QtWidgets.QApplication.translate("MainWindow", "00.000-000", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "CEP", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Bairro", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Município", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "UF", None, -1))
        self.grp_estrangeiro.setTitle(QtWidgets.QApplication.translate("MainWindow", "Estrangeiro", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Cidade", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "País", None, -1))
        self.gpr_contatos.setTitle(QtWidgets.QApplication.translate("MainWindow", "Contatos", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Tel 1", None, -1))
        self.edt_tel1.setInputMask(QtWidgets.QApplication.translate("MainWindow", " 0000 0000", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "Fax", None, -1))
        self.edt_tel3.setInputMask(QtWidgets.QApplication.translate("MainWindow", " 0000 0000", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Tel 2", None, -1))
        self.edt_tel2.setInputMask(QtWidgets.QApplication.translate("MainWindow", " 0000 0000", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "DDD", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "DDD", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "DDD", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "e-mail", None, -1))
        self.gpr_simples.setTitle(QtWidgets.QApplication.translate("MainWindow", "Simples", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Optante", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Data Opção", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "Data Exclusão", None, -1))
        self.grp_sit_especial.setTitle(QtWidgets.QApplication.translate("MainWindow", "Situação Especial", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "Situação", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "Data Situação", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Natureza Jurídica", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Data de início da Atividade", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Capital Social", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "MEI", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "Porte", None, -1))
        self.grp_situacao.setTitle(QtWidgets.QApplication.translate("MainWindow", "Situação", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Data da Situação", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Motivo da situação", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_geral), QtWidgets.QApplication.translate("MainWindow", "Geral", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_socios), QtWidgets.QApplication.translate("MainWindow", "Sócios", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "CNAE Principal", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cnaes), QtWidgets.QApplication.translate("MainWindow", "CNAES", None, -1))
        self.commandLinkButton.setText(QtWidgets.QApplication.translate("MainWindow", "Abrir no Navegador", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "Nível", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mapa), QtWidgets.QApplication.translate("MainWindow", "Grafo", None, -1))
        self.lbl_cnpj.setText(QtWidgets.QApplication.translate("MainWindow", "CNPJ: ", None, -1))
        self.edt_cnpj.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Digite aqui o CNPJ que deve ser consultado na base de dados.</p></body></html>", None, -1))
        self.edt_cnpj.setInputMask(QtWidgets.QApplication.translate("MainWindow", "00.000.000/0000-00", None, -1))
        self.btn_pesquisar.setText(QtWidgets.QApplication.translate("MainWindow", "&Pesquisar", None, -1))
        self.btn_limpar.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Limpar Pesquisa.</p></body></html>", None, -1))
        self.btn_limpar.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Razão Social", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Nome Fantasia", None, -1))

from PySide2.QtWebEngineWidgets import QWebEngineView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

